kind: pipeline
name: jjvargass_qa_ci

steps:
- name: check_readme
  image: python:2.7
  commands:
  - python qa/check_readme.py
  when:
    branch:
    - develop
    - release/*
    event:
    - push

- name: check_branch
  image: python:2.7
  commands:
  - pip install gitpython
  - python qa/check_branch.py
  when:
    branch:
    - develop
    - release/*
    - feature/*
    event:
    - push

- name: check_commits
  image: python:2.7
  commands:
  - pip install gitpython
  - python qa/check_commits.py
  when:
    branch:
    - develop
    - release/*
    event:
    - push

- name: publish_dockerhub
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: ${DRONE_REPO}
    tags:
      - ${DRONE_COMMIT:0:7}
      - latest
  when:
    branch:
    - develop
    - master
    event:
    - push

- name: notify_telegram
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: TELEGRAM_TOKEN
    to:
      from_secret: TELEGRAM_TO
    format: html
    message: >
      {{#success build.status}}
        ✅ <a href="{{build.link}}">SUCCESS</a> <b>Build #{{build.number}}</b> (type: <code>{{ build.event }}</code>)
        <b>Repo:</b><code>{{repo.name}}</code> <b>Branch:</b><code>{{commit.branch}}</code>
        <b>Commit:</b> <a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        <b>Autor:</b>{{commit.author}} <code>&#128526 </code>
      {{else}}
        ❌ <a href="{{build.link}}">FAILURE</a> <b>Build #{{build.number}}</b> (type: <code>{{ build.event }}</code>)
        <b>Repo:</b><code>{{repo.name}}</code> <b>Branch:</b> <code>{{commit.branch}}</code>
        <b>Commit:</b> <a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        <b>Autor:</b>{{commit.author}} <code>&#128549 </code>
      {{/success}}
  when:
    branch:
    - develop
    - release/*
    - master
    status:
    - failure
    - success
