kind: pipeline
name: jjvargass_qa_ci

steps:
- name: check_readme
  image: jjvargass/qa_develoment:0.1
  commands:
  - python /app/check_readme.py
  when:
    branch:
    - develop
    - release/*
    event:
    - push

- name: check_branch
  image: jjvargass/qa_develoment:0.1
  commands:
  - python /app/check_branch.py
  when:
    branch:
    - develop
    - release/*
    event:
    - push

- name: check_commits
  image: jjvargass/qa_develoment:0.1
  commands:
  - python /app/check_commits.py
  when:
    branch:
    - develop
    - release/*
    event:
    - push

- name: publish_to_ecr
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_acess_key
    region:
      from_secret: aws_region
    repo: jjvargass
    tags:
      - latest
  when:
    branch:
    - develop
    - release/*
    - master
    event:
    - push

# - name: run_sonar_scanner
#   image: timbru31/java-node
#   commands:
#     - export RELEASE=4.2.0.1873
#     - apt-get install curl grep sed unzip nodejs npm
#     - curl --insecure -o ./sonarscanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$RELEASE-linux.zip
#     - unzip sonarscanner.zip
#     - rm sonarscanner.zip
#     - rm -rf sonar-scanner-$RELEASE-linux/jre
#     - sed -i 's/use_embedded_jre=true/use_embedded_jre=false/g' ./sonar-scanner-$RELEASE-linux/bin/sonar-scanner
#     - cp sonar-project.properties ./sonar-scanner-$RELEASE-linux/conf/sonar-scanner.properties
#     - sonar-scanner-$RELEASE-linux/bin/sonar-scanner -X
#   when:
#     branch:
#     - develop
#     - release/*
#     event:
#     - push

# - name: nodejs_build
#   image: node:13.8.0
#   commands:
#   - npm i
#   - npm run-script build
#   when:
#     branch:
#     - develop
#     - release/*
#     - master
#     event:
#     - push

# - name: publish_to_S3
#   image: plugins/s3
#   settings:
#     bucket: bcdesarrolloci
#     access_key:
#       from_secret: AWS_ACCESS_KEY_ID
#     secret_key:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     region: us-east-1
#     source: dist/**/*
#     target: /
#     strip_prefix: dist/
#   when:
#     branch:
#     - develop
#     - release/*
#     - master
#     event:
#     - push


# - name: notify_telegram
#   image: appleboy/drone-telegram
#   settings:
#     token:
#       from_secret: TELEGRAM_TOKEN
#     to:
#       from_secret: TELEGRAM_TO
#     format: html
#     message: >
#       {{#success build.status}}
#         ✅ <a href="{{build.link}}">SUCCESS</a> <b>Build #{{build.number}}</b> (type: <code>{{ build.event }}</code>)
#         <b>Repo:</b><code>{{repo.name}}</code> <b>Branch:</b><code>{{commit.branch}}</code>
#         <b>Commit:</b> <a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
#         <b>Autor:</b>{{commit.author}} <code>&#128526 </code>
#       {{else}}
#         ❌ <a href="{{build.link}}">FAILURE</a> <b>Build #{{build.number}}</b> (type: <code>{{ build.event }}</code>)
#         <b>Repo:</b><code>{{repo.name}}</code> <b>Branch:</b> <code>{{commit.branch}}</code>
#         <b>Commit:</b> <a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
#         <b>Autor:</b>{{commit.author}} <code>&#128549 </code>
#       {{/success}}
#   when:
#     branch:
#     - develop
#     - release/*
#     - master
#     status:
#     - failure
#     - success


# - name: slack_notify
#   image: plugins/slack
#   settings:
#     webhook:
#       from_secret: SLACK_AND_WEBHOOK
#     channel: ci-develop
#     link_names: true
#     template: >
#       {{#if build.pull }}
#         *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
#       {{else}}
#         *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
#       {{/if}}
#       *Repo:* {{ repo.name }}
#       *Branch:* <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
#       *Commit:* <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

#       Author: {{ build.author }}

#       <{{ build.link }}|Visit build page ↗>
#   when:
#     branch:
#     - dev
#     - test
#     - master
#     status:
#     - failure
#     - success