kind: pipeline
name: jjvargass_qa_ci

steps:
- name: check_readme
  image: jjvargass/qa_develoment:latest
  commands:
  - python /app/check_readme.py
  when:
    branch:
    - develop
    - release/*
    event:
    - push

- name: check_branch
  image: jjvargass/qa_develoment:latest
  commands:
  - python /app/check_branch.py
  when:
    branch:
    - develop
    - release/*
    event:
    - push

- name: check_commits
  image: jjvargass/qa_develoment:latest
  commands:
  - python /app/check_commits.py
  when:
    branch:
    - develop
    - release/*
    event:
    - push

- name: publish_to_ecr
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACESS_KEY
    region:
      from_secret: AWS_REGION
    repo: jjvargass
    tags:
      - latest
  when:
    branch:
    - develop
    - release/*
    - master
    event:
    - push


- name: notify_telegram
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: TELEGRAM_TOKEN
    to:
      from_secret: TELEGRAM_TO
    format: html
    message: >
      {{#success build.status}}
        ✅ <a href="{{build.link}}">SUCCESS</a> <b>Build #{{build.number}}</b> (type: <code>{{ build.event }}</code>)
        <b>Repo:</b><code>{{repo.name}}</code> <b>Branch:</b><code>{{commit.branch}}</code>
        <b>Commit:</b> <a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        <b>Autor:</b>{{commit.author}} <code>&#128526 </code>
      {{else}}
        ❌ <a href="{{build.link}}">FAILURE</a> <b>Build #{{build.number}}</b> (type: <code>{{ build.event }}</code>)
        <b>Repo:</b><code>{{repo.name}}</code> <b>Branch:</b> <code>{{commit.branch}}</code>
        <b>Commit:</b> <a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        <b>Autor:</b>{{commit.author}} <code>&#128549 </code>
      {{/success}}
  when:
    branch:
    - develop
    - release/*
    - master
    status:
    - failure
    - success
